<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Run on Chrome"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="9.296">
  <properties />
            <testcase name="TC_01_Add_Product_To_Cart" time="9.296" classname="DemoProject.AddProducts.TS_03_AddProductToCart">
                <failure type="java.lang.AssertionError"
                  message="expected [xYou have no items in your shopping cart.] but found [You have no items in your shopping cart.]"
              >
<![CDATA[java.lang.AssertionError: expected [xYou have no items in your shopping cart.] but found [You have no items in your shopping cart.]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:442)
  commons.BaseTest.checkEquals(BaseTest.java:180)
  commons.BaseTest.verifyEquals(BaseTest.java:192)
  DemoProject.AddProducts.TS_03_AddProductToCart.TC_01_Add_Product_To_Cart(TS_03_AddProductToCart.java:87)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
  org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:750)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
